### ISSUE TITLE
POI 상세 헤더에 스크랩 전체 개수가 업데이트 되지 않는 문제를 수정합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1068]
## 문제

POI 상세에서 저장/저장취소 시 헤더영역의 전체 스크랩 개수가 업데이트 되지 않습니다.

## 기대

저장/저장취소 시 전체 스크랩 개수가 업데이트 됩니다.

**Comment by inbeom** [comment]
해결되었습니다.
