### ISSUE TITLE
badge, tag-label 컴포넌트를 분리 및 중복코드 리펙토링 합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1171]
## 설명

triple-document 문서 요소 컴포넌트(ElementSets) Itinerary(지도, 추천코스) 컴포넌트에 badge, tag-label 컴포넌트를 재사용 가능하도록 분리합니다.

original issue: #1166 에서 분리되어 등록된 이슈 입니다.

## 변경 필요사항

- [ ] badge 컴포넌트를 재사용 가능하도록 분리합니다. (기존에 구현되어 있는 유사한 컴포넌트도 체크)
- [ ] tag-label 컴포넌트를 재사용 가능하도록 분리합니다.
- [ ] use-safety-poi 훅 함수를 재사용 가능하도록 분리하고 내부에서 사용되는 타입정의를 공통화합니다.
  - titicacadev/triple-content 내에 있는 타입정의를 참조하면 좋을꺼 같습니다.
- [ ] use-handle-add-poi-to-trip 훅 함수를 재사용 가능하도록 분리하고 내부에서 사용되는 타입정의를 공통화합니다.
  - 이 함수는 POI 를 일정에 담기 위한 앱 기능을 context 값을 참조해 호출 할 수 있는 공통기능입니다.

**Comment by inbeom** [comment]
요것도 우선순위 낮음으로 분류하겠습니다.
