### ISSUE TITLE
지도,추천코스 스크롤 시 추천코스의 끝 지점까지 맵 영역을 상단 고정을 유지시킵니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1196]
## 설명

이건 그냥 개선하면 좋을꺼 같아서 아이디어를 작성해봅니다. 아마 컨텐츠쪽에서 요구사항이 생길꺼 같네요.
지도,추천코스의 경우 코스가 길어지면 스크롤 시 지도가 위로 사라져버리는데 이걸 추천코스의 끝나는 지점까지 상단 탑 영역에 고정할 수 있으면 좋을꺼 같습니다.

비슷한 UX 가 방콕/다낭/타이베이 도시메인 > 여행준비10분완성(지니) 카드 > 일정짜기 결과 페이지나 호텔 예약하기 기능에서 비슷한 UX 를 확인할 수 있습니다.

**Comment by inbeom** [comment]
패키지 단계에서 풀어야 하는 문제는 아닐 것 같습니다. 각 서비스 도메인에서 챙기겠습니다!
