### ISSUE TITLE
캘린더 컴포넌트 스타일을 개선합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1202]
## 설명

항공에서 왕복/편도에서 사용하는 캘린더 컴포넌트가 각각 다릅니다. (RangePicker/DayPicker)

최근 왕복/편도 검색조건 UI 개선 작업을 하면서 왕본 편도 전환하는 탭이 추가되었는데 이때 RangePicker 와 DayPicker 가 상호 전환되면서 스크린샷과 같이 여백값들이 달라서 그런지 다소 이상해보입니다.

## 스크린샷

![Kapture 2021-02-01 at 16 19 02](https://user-images.githubusercontent.com/145777/106426642-539d4b00-64a9-11eb-9c82-7d73855a960f.gif)

## 기대

RangePicker 와 DatePicker 의 날짜들의 정렬이 동일하게 표시될 수 있도록 스타일을 개선합니다.

**Comment by inbeom** [comment]
(아직도 발생한다면) 항공 도메인에서 논의해야 할 이슈로 보여요. 닫겠습니다!
