### ISSUE TITLE
create-triple-app, 각 서비스에 가지고 있는 with-asset-prefix 함수를 공통화합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1258]
이 함수의 경우 create-triple-app 포함, 대부분의 서비스에서 각자 가지고 있는 `with-asset-prefix` 를 이쪽으로 들고 오면 좋을꺼 같으네요? PR scope 가 커지니 이슈로 일단 분리해놔볼께요.

_Originally posted by @rhiokim in https://github.com/titicacadev/triple-frontend/pull/1256#r586113260_

## 설명
기존에 with-assets-prefix 함수는 이미지나 아이콘 에셋의 경로에 basePath 를 넣어주기 위해서 구현되어 create-triple-app 에 구현되어 있었는데 next.js 에서 basePath 를 지원하기 시작했고 TF 에서도 envProvider 를 통해서 context 값으로 basePath 를 느슨하게 의존성을 갖을 수 있게되었이니 Link 컴포넌트에 맴버 함수로 영입하고 공통화하면 어떨까요?

### AS-IS

```diff
- import { withAssetPrefix } from '../src/utils/with-asset-prefix'
+ import { addBasePath, LocalLink } from '@titicaca/router'

const A = styled.div`
-  background-image: url(${withAssetPrefix(
+  background-image: url(${addBasePath(
          '/static/images/img-trip-arrow@3x.png'
  )})
`

function B() {

  return (
    <>
     <A />
     <LocalLink ... />
    </>
  )
}
```

### TO-BE

**Comment by inbeom** [comment]
현재는 큰 요구가 보이지 않는 것 같습니다. 필요해질 때 다시 검토해보겠습니다!
