### ISSUE TITLE
동일 아티클 내 앵커링 기능 구현

### ISSUE THREAD

**Issue by dddeok** [titicacadev/triple-frontend#1278]
## 설명

- 관련 쓰레드 https://titicaca.slack.com/archives/C6DNCMXUL/p1615857093002500
- 동일 아티클 내 앵커링 기능 구현
- 현재 앵커 기능의 경우, url 해쉬값을 바탕으로 지정된 앵커 포지션으로 찾아가게 되는데 내부에서 url을 변경시킬 수 있는 컴포넌트가 존재하지 않음

**Comment by zhsks528** [comment]
[`standard-action-handler`의 `/web-action/scroll-to-element`으로 구현했습니다.](https://github.com/titicacadev/triple-frontend/blob/main/packages/standard-action-handler/src/scroll-to-element.ts)

- 사용 방법은 /web-action/scroll-to-element?hash="해당 위치로 이동시키고 싶은 값" 을 입력하면 됩니다.
- [예시 페이지](6ab4496b-df35-4979-a99c-e1bd102db3d2)입니다.
