### ISSUE TITLE
이미지 크게보기 

### ISSUE THREAD

**Issue by pgs787** [titicacadev/triple-frontend#1313]
- 호텔의 본문 사진/투어티켓 대표사진 선택 시 크게 보기가 존재하지 않음
- 관련 슬랙
https://titicaca.slack.com/archives/C6DNCMXUL/p1618395947026000?thread_ts=1598337756.008700&cid=C6DNCMXUL

**Comment by drakang4** [comment]
https://github.com/titicacadev/triple-frontend/pull/3165
