### ISSUE TITLE
pricing 컴포넌트의 composability 를 향상시킵니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1330]
## 배경

pricing 컴포넌트의 가격표시 영역 및 버튼등을 분리하여 조립하여 사용하기 쉽도록 composability 를 향상시킵니다.

항공,숙소,투어티켓 상품목록 화면 모음 - https://www.figma.com/file/bf2voyPtVHMXk481q16K6M/%EB%B9%84%EC%A6%88-%EC%84%9C%EB%B9%84%EC%8A%A4%EB%B3%84-%EC%83%81%ED%92%88-%EB%AA%A9%EB%A1%9D?node-id=0%3A1

<img width="865" alt="스크린샷 2021-04-22 오전 11 03 11" src="https://user-images.githubusercontent.com/145777/115644931-60b83080-a35a-11eb-8a4d-bb57e06e30b9.png">

자세한 내용: https://titicaca.slack.com/archives/CEEPB4TDY/p1618997390128700

**Comment by inbeom** [comment]
구체적인 이니셔티브가 생기면 다시 살펴보기로 하겠습니당. 많은 관심 감사합니다!
