### ISSUE TITLE
POI 상세, 상품 엔드 대표이미지 등이 로딩되기 전에 탭하여 이미지 뷰어를 띄우면 이미지 로딩이 되지 않는 문제를 개선이 필요합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1335]
## 배경

인터넷이 느리거나 손이 너무 빠른 사람의 경우 POI 엔드나, 상품 엔드에 진입할 때 대표 이미지가 로딩되기 전에 이미지를 탭하여 이미지 뷰어를 띄우면 이미지가 로딩되지 않은 이슈가 있네요.  자세한 재현은 슬랙 쓰레드에 영상을 참조해주세요.

- https://titicaca.slack.com/archives/C01CHRQBP1U/p1619156786429400

> 저는 더 이상 재현해볼 수 없는 피지컬 모드가 되었습니다. 🙇🏻 
> iOS 에서는 재현이 잘 안되는 느낌이네요.

**Comment by inbeom** [comment]
안드로이드에서만 재현되는 것 같은데, 지라/슬랙에서 논의 이어가겠습니다. TF 모듈의 이슈는 아닐 듯합니다.
