### ISSUE TITLE
Stack 컴포넌트에 gap prop을 추가합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1339]
## 배경

Stack 컴포넌트이 추가되면서 List 컴포넌트가 가지고 있던 일부 역할이 중복됩니다.

List 컴포넌트가 가지고 있는 `verticalGap` prop 을 Stack 으로 위임하고 List 가 가지고 있던 중복되는 역할을 `Stack` 컴포넌트로 변경합니다.

original - https://github.com/titicacadev/triple-frontend/pull/1333#pullrequestreview-644261100

**Comment by inbeom** [comment]
큰 요구는 없네요. 닫겠습니다.
