### ISSUE TITLE
[RFC] ModalContext를 추가합니다.

### ISSUE THREAD

**Issue by torres-triple** [titicacadev/triple-frontend#1345]
## 배경

`TripleDocument`에서 모달을 사용하게 되면서 발생한 문제입니다.

모달을 사용하고있는 `DocumentElement`가 한페이지에 여러개 있는경우,
동일한 `uriHash`값을 쓰는 `Modal 컴포넌트` 가 한페이지에 여러개생겨 모달이 한번에 여러개 열리는 현상이 발생했습니다.

일단은 modalHash에 couponId를 식별자로 사용하여 해결한 상태입니다만 [참고코드](https://github.com/titicacadev/triple-frontend/pull/1322/files#diff-54438d15024041a820f6eabcf8414f771b53782ec0b110c0180a4dbf560f7a31R63)
비슷한 형태의 모달이 페이지에 여러개 생기는것은 불필요한 동작인것 같습니다.

또한 Modal이 컴포넌트에 종속되는것보다는 페이지에 종속되어있는게 좀더 이쁜 구조가 나올것같습니다.

## 스펙
Provider Render
```jsx
<ModalContext.Provider>
  {children}
  <Alert />
  <Modal />
  <Confirm />
  <TransitionModal />
</ModalContext.Provider>
```

Context Value Interface
```typescript
interface ModalContextValue {
  action: {
    openModal: (
      type: ModalType,
      options: {
        title?: string
        message?: string
        icon?: IconType
        confirmTitle?: string
        cancelTitle?: string
        onClose?: () => void
        onConfirm?: () => void
      }
    ) => Promise<void>
  }
}
```

**Comment by inbeom** [comment]
#1879 에서 이어가고, 이 이슈는 닫겠습니당
