### ISSUE TITLE
[triple-document] 아티클에 임베딩되는 호텔 POI에도 성급 룰을 적용합니다

### ISSUE THREAD

**Issue by nosiar** [titicacadev/triple-frontend#1368]
관련 코멘트
https://github.com/titicacadev/triple-hotels-web/pull/2245#issuecomment-841924899

**Comment by dongoc** [comment]
[호텔의 성급이 없을 때 카테고리를 표시하는 기획](https://github.com/titicacadev/triple-frontend/issues/1368)은 이후 [저장 수 노출 표시](https://github.com/titicacadev/triple-hotels-web/pull/2372)로 바뀌면서 없어진 듯 합니다. ([관련 기획 문서](https://titicaca.atlassian.net/wiki/spaces/BUS/pages/2400485416/SP.70))
