### ISSUE TITLE
고정 여백을 props 로 내려 받을 수 있도록 합니다.

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#1393]
## 배경

PoiListElement 컴포넌트를 사용하고 있는 숙소 엔드 페이지에서 네비영역에 이벤트 필터가 추가되면서 여러가지 요소들의 노출 조건에 따라 기본 여백값의 collapsing 이 기대한 것과 같이 동작하지 않는 이슈가 있어 숙소 엔드에서 여백을 확장하였습니다. 

PoiListElement < ExtendedPoiListElmenet 에 고정된 여백(padding)값을 nullable 시 고정값으로 갖고 props 로 여백을 받아 확장될 수 있도록 합니다. 

link - https://github.com/titicacadev/triple-hotels-web/pull/2247
> 숙소 숙박대전 대응하면서 공통 컴포넌트 css 를 확장한 요소를 해결합니다.

**Comment by inbeom** [comment]
추가 요구가 아직 없는 것 같습니다. 닫아둘게요!
