### ISSUE TITLE
API 응답이 201일 때 fetcher의 응답 타입을 설정

### ISSUE THREAD

**Issue by zprime0920** [titicacadev/triple-frontend#1422]
현재 응답 타입이 {}을 확장하는 타입 파라미터이기 때문에 아무 응답이 없는 201을 명확하게 표시할 방법이 없습니다.

**Comment by inbeom** [comment]
Fetcher 개편하면서 해결되었습니다. https://github.com/titicacadev/triple-frontend/pull/1785
