### ISSUE TITLE
Color관련 코드를 정리합니다.

### ISSUE THREAD

**Issue by kooinsung** [titicacadev/triple-frontend#1523]
예전에 Color를 css variable를 활용하여서 사용할수 있도록 GlobalStyle에 추가했었습니다.
이를 좀더 적극적으로 사용할수 있도록 기존 레거시 코드를 제거합니다. Bracking Change가 되는데, 조심스럽게 다듬어 보겠습니다.

1. https://github.com/titicacadev/triple-frontend/blob/main/packages/color-palette/src/colors.ts 에 선언된 ColorSet를 Color명만 가지는 리터럴타입으로 변경하고, 코드는 제거
예) const colorSet = gray | gray20 ...

2. 현재 여럿 패키지에서 color나 backgroundColor를 prop를 받아서 rgba로 변환되는 코드를 css variable로 변경
예)
```
${({ backgroundColor }) =>
    backgroundColor && `background-color: rgba(${getColor(backgroundColor)});`} 

${({ backgroundColor }) =>
    backgroundColor && `background-color: var(--color-backgroundColor));`}```


3. getColor 제거

**Comment by drakang4** [comment]
단계를 나눠서 정리할 계획입니다.

1. TF 내부에서 color-palette getColor를 css variable로 변경 https://github.com/titicacadev/triple-frontend/pull/2280
3. web 프로젝트에서 color-palette 의존성 제거
4. TF에서 color-palette 패키지 제거
