### ISSUE TITLE
ESM을 사용합니다.

### ISSUE THREAD

**Issue by giwan-dev** [titicacadev/triple-frontend#1643]
[esm과 commonJS를 모두 지원하는 방법도 있나봅니다.](https://gist.github.com/aelbore/65a4d2e86c3326f36607db111a7b6887)

swc가 워낙 빠르니 tsc가 작업을 끝내기 전에 두 번 빌드해서 두 방식을 모두 지원하면 어떨까요?

얻을 수 있는 장점은 다음과 같습니다.

- 트리쉐이킹이 가능해집니다. #1522 참고

**Comment by drakang4** [comment]
commonjs + esm 같이 쓰면 [dual package hazard](https://nodejs.org/api/packages.html#dual-package-hazard)라는 두 모듈이 꼬이는 현상도 발생할 가능성도 있다고 해서
[pure esm](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c) 도 괜찮을 것 같아요.

[next 12](https://nextjs.org/blog/next-12#es-modules-support-and-url-imports)가 esm을 지원하고,
[jest](https://jestjs.io/docs/ecmascript-modules)는 설정이 조금 필요한데 가능은 하고,
storybook은 v7부터 지원되는 것 같습니다. https://github.com/storybookjs/storybook/issues/9854
