### ISSUE TITLE
`Modals` 링크 컴포넌트 적용 이슈

### ISSUE THREAD

**Issue by pgs787** [titicacadev/triple-frontend#1744]
https://github.com/titicacadev/triple-frontend/issues/1140 이 작업에서 파생되는 이슈입니다.

`확인` 버튼을 제공하는 모달 케이스는 무조건적으로 onClick 핸들러로 라우팅을 이용해야 합니다.
이와 같은 케이스를 해결하기 위해 링크 컴포넌트를 사용할 수 있도록 버튼 마크업을 확장해야 하는데
모달의 구조를 개선해야하는 부분이라 위의 해당 이슈를 해결하고 추후에 작업을 진행해보겠습니다! 🙇

<img width="320" alt="스크린샷 2021-12-22 오후 2 46 36" src="https://user-images.githubusercontent.com/43316372/147042026-f3644130-5d0a-4261-8f99-32339c09dcd7.png">

**Comment by drakang4** [comment]
https://github.com/titicacadev/triple-frontend/pull/2228 에서 Modal을 compound component 구조로 변경했습니다. `Modal.Action` 컴포넌트에 `as` prop을 전달해서 취소나 확인 버튼을 링크로 만들 수 있습니다. 

Alert 또는 Confirm 컴포넌트는 하위호환을 위해 그대로 기존 구조로 남아 있어서 사용이 불가능해서, 이런 커스터마이징이 필요한 경우에는 Alert, Confirm 대신 Modal을 사용하는 것을 권장합니다.

https://github.com/titicacadev/triple-frontend/blob/181bffe70fa98b7773eed2ea9c212df31432eea4/packages/modals/src/modal/modal.stories.tsx
