### ISSUE TITLE
date-picker의 오늘 표시 라벨과 상관없는 chromatic 테스트 작성

### ISSUE THREAD

**Issue by zprime0920** [titicacadev/triple-frontend#1753]
https://www.chromatic.com/test?appId=617b7c4431c922004a42c7cc&id=61c4029102f500003a993df8

chromatic 업로드 날짜가 바뀌면 date-picker의 오늘 표시 라벨이 변경으로 감지됩니다.

하루에 한 번은 무조건 발생할 수 있는 문제이기 때문에 이를 우회할 방법이 있다면 적용하면 좋겠습니다.

ex) 오늘 날짜를 모킹하여 스토리북에선 항상 일정한 날짜를 표시

**Comment by inbeom** [comment]
https://github.com/boblauer/MockDate 이런 게 있네요. Storybook decorator로 붙여서 쓰면 해결할 수 있을 것 같습니당

**Comment by inbeom** [comment]
closed by #2017
