### ISSUE TITLE
triple-document 추천코스 UI 스냅샷에 지도가 들어가는 문제

### ISSUE THREAD

**Issue by zprime0920** [titicacadev/triple-frontend#1843]
[Google Maps가 스냅샷에 들어가고 있습니다.](https://www.chromatic.com/test?appId=617b7c4431c922004a42c7cc&id=61e0c76393786f003a7592ee)
이를 우회하는 방안이 필요합니다.

**Comment by pgs787** [comment]
#1842 랑 같이 스토리북 파라미터로 스냅샷을 disabled 적용해놓을까요? 🤔

**Comment by zprime0920** [comment]
> #1842 랑 같이 스토리북 파라미터로 스냅샷을 disabled 적용해놓을까요? 🤔

흠.. 지도 영역만 스냅샷에서 제외하고 싶지만 그런 기능은 없겠죠..?ㅠㅠ
추천 코스 UI가 복잡한 편이라 UI 스냅샷 만들어놓으면 좋을 거 같은데 아쉽네요.

**Comment by pgs787** [comment]
음 .. 찾아보고 있는데 잘 안보이네요 ㅠㅠ 이따가 요거 관련해서 헤론이랑 이야기 한 번 나눠보겠습니다!

**Comment by drakang4** [comment]
@zprime0920 @pgs787 
https://www.chromatic.com/docs/ignoring-elements#ignore-dom-elements
특정 엘리먼트를 스냅샷에서 제외할 수 있는 방법이 있습니다!

**Comment by pgs787** [comment]
오홋 한 번 설정해보겠습니다! 🙇

**Comment by pgs787** [comment]
> 그러고보니 레퍼럴 설정으로 지도가 안 나오게 된 것 같은데, 그러면 오류 화면이 계속 뜰 테니 스냅샷이 바뀔 일이 없을 것 같기도하군요ㅋㅋㅋ

앗 그러고 보니 그렇네요 .... ㅋㅋ
