### ISSUE TITLE
정리가 필요한 패키지 목록

### ISSUE THREAD

**Issue by zhsks528** [titicacadev/triple-frontend#1998]
[패키지별 린트 활성화 이슈](https://github.com/titicacadev/triple-frontend/issues/1755)를 처리하면서, 의미가 다소 약해진 패키지들이 존재하는 것 같습니다. 
논의를 통해, 수정 및 제거하면 좋을 것 같습니다.

논의가 필요한 패키지들
1. static-page-contents 
2. style-box

**Comment by drakang4** [comment]
https://titicaca.atlassian.net/wiki/spaces/dev/pages/3168272443/TF

- 적절하게 항시 사용되는 패키지들
	- action-sheet
	- popup
	- core-elements
	- modals …
- 방향을 잃어가는 패키지들
	- icons
	- style-box …
- 도메인에서 특정한 곳에서만 사용하는 패키지들
	- booking-completion
	- hub-form
	- resource-list-element …

**Comment by kooinsung** [comment]
요거 아직 일부만 작성한거라서, 좀더 정리 해보겠습니다.
