### ISSUE TITLE
위젯

### ISSUE THREAD

**Issue by drakang4** [titicacadev/triple-frontend#2130]
triple-frontend에서 위젯(widget)이라는 개념으로 모듈의 관심사를 구분해보면 좋을 것 같습니다.

### 위젯이 뭔가요?

- UI에 필요한 데이터의 query 로직이 포함되어 필요한 값을 서버나 네이티브 앱에서 알아서 가져옵니다.
- 데이터 mutation이 필요하다면 서버나 네이티브에 앱에 관련된 요청을 보낼 수 있습니다.
- 로딩이나, 에러 상태 UI를 보여줄 수도 있습니다.
- 이런 로직이 포함되어 있으므로 필요한 페이지에서 적은 코드로 쉽게 가져다 쓸 수 있습니다.

### 위젯에는 얼마나 많은 자유도를 주어야 할까요?

- 위젯과 presentational 컴포넌트 둘 다 export 해주는 게 좋을까요?
- css prop을 허용해야 할까요?

### 예시 

이미 triple-frontend에는 위젯으로 분류할만한 패키지들이 존재합니다.

data-picker

- 공휴일 데이터를 서버에서 가져오는 로직이 포함되어 있습니다.

review

- 서버에서 리뷰 데이터를 가져오는 로직이 포함되어 있습니다.
- 좋아요를 누르거나 취소할 수 있는 로직이 포함되어 있습니다.
- 네이티브 앱에서 동영상 자동 재생 설정 값을 가져와서 video autoplay를 할지 말지 구분할 수 있습니다. (예정)

ref: https://alexei.me/blog/widget-driven-development/

**Comment by choisohyun** [comment]
레퍼런스와 예시 코드들 읽고왔는데 너무 좋습니다 👍
코드를 처음 보는 사람 입장에서도 위젯에서 데이터 query 로직이 포함되어 있으면 컴포넌트 흐름이 파악이 잘 될것 같습니다. 
데이터를 prop으로 받아쓰게 된다면 컴포넌트 사용부를 다른 레포지토리에서 찾아봐야 한다는 점에서.. 여러 레포지토리를 돌아다녀야 하네요,,

하나 더 생각나는 부분은 필요한 페이지에서 가져다 쓰는 코드가 작아질수록 위젯의 몸집이 커져버릴 수도 있겠다는 생각이 들었습니다. 요런거만 적절히 분리하면 prop 개수라던가 prop drilling 현상도 막을수 있을것 같네요 

> 위젯과 presentational 컴포넌트 둘 다 export 해주는 게 좋을까요?

위젯 기반으로 간다면 presentational 컴포넌트는 export 하지 않고 다른 위젯으로 생성해서 사용하는 방식도 있어 보이네요
하위호환성을 가진다면 둘다 export 이후 fade out 시켜도 될것같구요!

> css prop을 허용해야 할까요?

작은 부분에서 커스텀이 필요할수도 있다면 허용하는것도 괜찮을것 같아보여요!

**Comment by choisohyun** [comment]
<img width="1637" alt="Screen Shot 2022-10-07 at 5 12 17 PM" src="https://user-images.githubusercontent.com/30427711/194505686-cc31c38a-509a-4725-a4c7-1d0a0e362b1c.png">

[아토믹 디자인을 활용한 디자인 시스템 도입기](https://fe-developers.kakaoent.com/2022/220505-how-page-part-use-atomic-design-system/)를 참고하여 컴포넌트를 작은 것부터 분류해 보았습니다.
`Molecule, Organism, Template` 까지를 크게 위젯으로 설정해볼 수 있을 것 같습니다.

API 호출부분이나 복잡한 로직을 훅으로 분리해서 위젯에서 부르도록 Container를 추가해서 래핑한다면 가능할 것 같아 보이기는 하는데.. (뇌피셜)
사실 컴포넌트 적어놓으니 많아서 어디부터 봐야할지 감이 안잡히네요 ㅎㅎㅎ 

추가로 분류해보니까 스토리북 안에서도 `원시 컴포넌트 / 위젯 컴포넌트` 식으로 대분류가 추가된다면 컴포넌트 체크할 때 도움이 되지 않을까 싶은 생각이 들었습니다!
