### ISSUE TITLE
Headless 컴포넌트 기반으로 접근성 개선

### ISSUE THREAD

**Issue by drakang4** [titicacadev/triple-frontend#2131]
컴포넌트들의 접근성이 전체적으로 미약한 상황입니다.

접근성 제대로 지켜서 [모든 것](https://www.w3.org/TR/wai-aria-practices-1.2/)을 처음부터 직접 구현하기에는 굉장히 많은 리소스가 필요할 것이라
접근성을 위해서는 라이브러리를 사용하는 것이 좋을 것 같습니다.

접근성만 구현되어 있고 스타일이 없어서 자유롭게 스타일링 가능한 이런 라이브러리를 [Headless 컴포넌트 라이브러리](https://jbee.io/react/headless-concept/)라고 부르고 그 중 많이 사용되는 후보를 골라봤습니다.

- https://github.com/radix-ui/primitives
  - React 최소버전 18부터 사용 가능함
  - Provider 필요하지 않음
- https://github.com/ariakit/ariakit
  - v2가 개발중인데 거의 1년 넘게 진행중이고 언제 스테이블 버전 나올지 모르겠음..
  - Provider가 필요함 (v1 기준)
- https://headlessui.com/
  - 컴포넌트 수가 적음
- https://react-spectrum.adobe.com/react-aria/
  - 어도비 오픈소스
  - Only hook 기반
  - 독자적인 click, touch 이벤트 처리 방식이 있음 https://react-spectrum.adobe.com/blog/building-a-button-part-1.html onClick 대신 onPress 라는 이름의 prop을 사용해야 함
- https://github.com/reach/reach-ui
  - 컴포넌트 수가 적음

개인적으로는 radix-ui가 가장 괜찮아 보입니다.

**Comment by choisohyun** [comment]
radix-ui로 테스트할 겸 dialog 컴포넌트를 변경 적용해 봤는데 생각보다 변경지점이 많네요 
https://www.radix-ui.com/docs/primitives/components/alert-dialog#custom-portal-container 이거 보고 했는데.. 예시처럼 딱 맞게 하려면 알맞은 태그를 찾아서 변경해야 하는거같아요🥲 prop과 type이 조금씩 달라서 싱크 맞추는 작업도 필요하구요

코드 보니까 훅으로 분리된 것들도 보이는데 요런걸 사용해서 키보드 인터렉션을 추가하면 어떨까 생각해봤습니다. (다른것도 챙겨야겠지만 주로 키보드 인터렉션에서 걸리는게 많더라구요!)

- https://github.com/radix-ui/primitives/blob/main/packages/react/use-escape-keydown/src/useEscapeKeydown.tsx
- https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/dialog/src/useDialog.ts, https://github.com/adobe/react-spectrum/blob/24afd2a1feeb81bb71001204e1f2c9fc986ae282/packages/%40react-spectrum/dialog/src/Dialog.tsx#L58

추가적으로 eslint plugin과 axe로 접근성 테스트도 할 수 있길래 첨부합니다!
- https://ko.reactjs.org/docs/accessibility.html#development-assistance

**Comment by drakang4** [comment]
> 코드 보니까 훅으로 분리된 것들도 보이는데 요런걸 사용해서 키보드 인터렉션을 추가하면 어떨까 생각해봤습니다. (다른것도 챙겨야겠지만 주로 키보드 인터렉션에서 걸리는게 많더라구요!)

저도 이런 점에서 hook only 라이브러리인 react-aria가 사용하기 더 좋을 것 같다는 생각을 처음에 했었어요. react-aria를 아직 저도 써보진 않았는데 한번 이걸로도 구현해보고 비교해보면 좋을 것 같아요

**Comment by drakang4** [comment]
> 추가적으로 eslint plugin과 axe로 접근성 테스트도 할 수 있길래 첨부합니다!

https://storybook.js.org/addons/@storybook/addon-a11y  스토리북에서 axe로 접근성 테스트 할 수 있게 해주는 이런 애드온도 있어요. 스토리북을 개발과 테스트 환경으로 쓰고 있어서 접근성 테스트도 스토리북에서 돌리면 좋을 것 같아요

**Comment by drakang4** [comment]
오랜 삽질 결과 https://github.com/floating-ui/floating-ui 이 최적이라고 귀결되었습니다.
