### ISSUE TITLE
[COMMON] 접근성에 맞게 구조를 수정합니다

### ISSUE THREAD

**Issue by appear** [titicacadev/triple-frontend#763]
1. div 안에 li 

![image](https://user-images.githubusercontent.com/27910236/82183209-8524b500-9920-11ea-88e1-14c24df678bd.png)

![image](https://user-images.githubusercontent.com/27910236/82183194-7fc76a80-9920-11ea-9263-cdaeff7aed3c.png)

2. alt가 없는 이미지 속성들 

![image](https://user-images.githubusercontent.com/27910236/82183486-0bd99200-9921-11ea-9532-9f39017c6f82.png)

**Comment by inbeom** [comment]
요것 포함 접근성 이슈는 #2131 로 몰아보겠습니다!
