### ISSUE TITLE
[RFC] StaticPageContents

### ISSUE THREAD

**Issue by rhiokim** [titicacadev/triple-frontend#772]
# [RFC] StaticPageContents
이용동의 정책, 각 서비스별 서비스 정책등을 static-page 리포를 통해 markdown 으로  공통으로 관리되고 있는데 각 서비스별로 해당 파일을 표시해야하는 경우가 발생하여 이 파일을 로딩하고 표시하는 공통 컴포넌트를 구현합니다.

## Spec & Usage

```ts
type StaticPageContentsProps = {
  /** 정적 페이지 파일명 */
  src: string
}
```

만약 아래의 예제와 같이 `src` props 의 값이 `hotel-service-policy.html` 인 경우 `https://github.com/titicacadev/triple-static-pages/src/hotel-service-policy.md` 의 `html` 파일을 로딩해 화면에 표시하게 됩니다.

```jsx
import StaticPageContents from ‘@titicaca/static-page-contents'
import Popup from ‘@titicaca/popup’  

const PolicyPopup = () => <Popup open={true}>
  <StaticPageContents src=“hotel-service-policy.html” />
  <StaticPageContents src=“air/reservation/private-policy.html” />
</Popup> 
```

## with custom style

경우에 따라 스타일을 적용해야 할 경우를 대응합니다.

```jsx
import StaticPageContents from ‘@titicaca/static-page-contents'
import Popup from ‘@titicaca/popup’  

const CustomStyleDiv = styled.div`
  color: red;
`

const PolicyPopup = () => <Popup open={true}>
  <CustomStyleDiv>
    <StaticPageContents src=“hotel-service-policy.html” />
  </CustomStyleDiv>
  <StaticPageContents src=“air/reservation/private-policy.html” />
</Popup> 
```

## 유의사항

* 로컬에서 해당 컴포넌트를 사용할 경우 커스텀서버에 proxy 적용이 필요합니다.
  - https://github.com/titicacadev/triple-air-web/blob/master/server/index.ts#L65-L72

**Comment by inbeom** [comment]
Closed by #802
