### ISSUE TITLE
[triple-document] 데스크탑 브라우저를 위한 Carousel 스크롤 추가

### ISSUE THREAD

**Issue by polysiya** [titicacadev/triple-frontend#955]
이미지와 POI, 임베디드 등 많은 경우에 horizontal-scrolling이 되는 `Carousel`을 사용하고 있습니다.
하지만 데스크탑 브라우저의 경우 일반 마우스로는 해당 콘텐츠를 횡스크롤 하는 것이 불가능합니다.
따라서 데스크탑 브라우저에서만 횡스크롤을 노출하는 responsive 스타일이 필요합니다.

**Comment by inbeom** [comment]
Closed by #1120
